### ISSUE TITLE
Cannot validate captcha

### ISSUE THREAD

**Issue by myleskadusale** [bonecms/laravel-captcha#1]
Hello

First I would like to thank you for creating this very useful library.
So I tried using your library it shows the captcha but when I validate it fails,
did I miss out something?
I followed all the steps.

It seems the captcha code that was saved in the session was not retained during validation.

I am using Laravel 5.3

Regards,
Myles

**Comment by shiv2144** [comment]
Exactly same issue i faced too today.
- All steps followed.
- When checked Session::get('captcha') was empty.
  I am also using Laravel 5.3
  Thanks...

**Comment by igoshev** [comment]
Hello! 
Thanks for the bug was found. 
Fixed in version 1.1.
