### ISSUE TITLE
Could not load image

### ISSUE THREAD

**Issue by rage5110** [bonecms/laravel-captcha#3]
Laravel ver. 5.4.36

After, following all the necessary steps - the captcha image outputs the alternate text, and inspector shows 'could not load image'.

Could this be a bug? or did I miss out on anything?

Added to provider hence, facade access.
Added config file.
Able to use captcha html output.

But failed to display, captcha image and outputs Alt.

**Comment by igoshev** [comment]
For Laravel 5.4 use v2.0 
https://github.com/igoshev/laravel-captcha/tree/v2.0
