### ISSUE TITLE
Not checking for case sensitive

### ISSUE THREAD

**Issue by bhattraideb** [bonecms/laravel-captcha#33]
I installed this package and working fine but case sensitive is not checking.

**Comment by khanzadimahdi** [comment]
i think captcha doesnt need to be case sensitive, as you see in most websites it is not case sensitive.

**Comment by igoshev** [comment]
Сapcha should not be case sensitive.

**Comment by bhattraideb** [comment]
Ok, then we should avoid displaying uppercase.
